### PR TITLE
Fixed Some Array Extensions Bugs

### PR DESCRIPTION
**Pull request by martindevans**
I started testing the `ArrayExtension` methods and discovered a bug in the `Add` and `GetOrResize` methods. Both methods internally call `Array.Resize`, but they never return the new array! This is probably because the method is very badly named and implies that it will somehow resize an existing array, this is not the case. To quote the docs:

> This method allocates a new array with the specified size, copies elements from the old array to the new one, and then replaces the old array with the new one.

---

The `GetOrResize` method was not used anywhere, so I simply deleted it.

The `Add` method was only used in the `CompileTimeStatics` class, which was using a `Type[]` as a map from `int -> Type`. Replaced this with an actual `Dictionary<int, Type>` instead, removing the need for the extension.

### CODE REVIEW

**Comment by genaray** [comment]
Thanks! Not on my PC right now, but having Arrays there ist intended due to the New lookup mechanism. Having dictionarys there ist extremely Bad for the lookups. So I would suggest to Just fix the Bug and leave the Arrays that way ^^

**Comment by martindevans** [comment]
Ah I did have a look for "hot" paths using this. If there's a new system on the way that uses this somewhere hot I'll have to move it back to arrays.

**Comment by martindevans** [comment]
Ok I've added back in the `Add` extension, covered it with tests and used in inside `ComponentRegistry`.

Fixed:
 - Modified array is returned (same as the other `Add` extensions)
 - `doublingCount` is never allowed to be zero
 - Negative index is caught

Changed:
 - `TypeToComponentType` and `Types` now return readonly wrappers over mutable private fields, instead of publicly exposing mutable fields.

**Review by genaray — APPROVED** [review]
Nice, great job! :)

**Pull request merged**
