### PR TITLE
Feature/sequence equals archetype comparer

### LINKED ISSUE #9: TryGetArchetype uses reference equality instead of SequenceEquals
In the World method `TryGetArchetype(Type[], out Archetype)` the backing `PooledDictionary` uses reference equality, which leads to unexpected behavior such as this:

```csharp
var archTypes1 = new Type[] { typeof(Transform) };
var archTypes2 = new Type[] { typeof(Transform) };

var entity1 = world.Create(archTypes1);
var entity2 = world.Create(archTypes2);
```

Creating 2 Archetypes in the World as `archTypes1` and `archTypes2` don't reference the same instance of `Type[]`.

The fix is quite easy, implement an `IEqualityComparer<Type[]>` that uses `SequenceEquals` and pass it to the `PooledDictionary` to use.

### PR DESCRIPTION
**Pull request by MindSwipe**
Fixes #9

### CODE REVIEW

**Review by genaray — APPROVED** [review]
Approved :)

**Comment by stefanomerotta** [comment]
I suggest not to use SequenceEqual in an equality compare because it takes an ienumerable as argument that will use the generic ienumerator implementation (that requires boxing and therefore allocation) even for the array.

Maybe it's better to implement an ad-hoc method with a loop for array types

**Comment by genaray** [comment]
> I suggest not to use SequenceEqual in an equality comparer because it takes an ienumerable as argument that will use the generic ienumerator implementation (that requires boxing and therefore allocation) even for the array.
> 
> Maybe it's better to implement an ad-hoc method with a loop for array types

Well thats possible, im gonna adjust that real quick. I think theres also a `.AsSpan().SequenceEquals()` if i saw that correctly, probably that one wont box :)

**Comment by genaray** [comment]
Should be fixed in [0597b26](https://github.com/genaray/Arch/commit/0597b263ea381a17d82b34da62c956a5293d618a) :) 
Now converting the type arrays to spans and iterate over them to prevent boxing aswell as bound checks. Should be fine now ^^

**Comment by stefanomerotta** [comment]
I can't check it properly now (I am not at My PC). Could you please leave the PR open so I can check it tomorrow (it's midnight for me now)? I would check the recent. NET improvements and find the Best one for this scenario that could be an hot path

**Comment by genaray** [comment]
> I can't check it properly now (I am not at My PC). Could you please leave the PR open so I can check it tomorrow (it's midnight for me now)? I would check the recent. NET improvements and find the Best one for this scenario that could be an hot path

Same for me, i actually need to go to sleep :D 
The PR already have been merged like an hour ago, but it will still be visible so take your time ^^

**Comment by stefanomerotta** [comment]
I just found that they already optimized the Enumerable.SequenceEqual when both collections are arrays, as reported in this article and related linked PR [. Net 6 improvements](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/)

In our case we could skip also the Enumerable.SequenceEqual type check and use the MemoryExtensions.SequenceEqual directly as you suggested in your previous comment

**Pull request merged**
