### PR TITLE
Support entity creation/deletion during a query

### PR DESCRIPTION
**Pull request by andreakarasho**
This solve https://github.com/genaray/Arch/issues/13
The problem was with the line:
`var destroyedChunk = archetype.Remove(ref entityInfo.Slot, out var movedEntityId);`
which moves the last entity to the destroyed entity index.
 When this happens `in Entity` [which is translated into `ref readonly Entity`] changes the reference to the moved entity, so Arch will recycle a valid ID.

Tested with the code below [and some other variations]
```csharp
        struct P { }

        var world = World.Create();
        var query = new QueryDescription()
        {
            All = new Core.Utils.ComponentType[] { typeof(P) },
        };

        for (int i = 0; i < 100; ++i)
            world.Create<P>();

        while (true)
        {
            world.Query(in query, (in Entity e) =>
            {
                world.Destroy(in e);
                var ee = world.Create<P>();
            });
        }
```

### CODE REVIEW

**Comment by genaray** [comment]
Looks promising, gonna test that out later :) This would be great ( and would reduce the usage of command buffers, i also have a first reworked version. You may look at it, it uses your API sugesstion #30 ).

Have you tested if it invalidates the world state ? The current queries move forward and im actually not sure what happens in the following case : 
```csharp

// Loop over all query entities and destroy them. 
world.Query(in desc, (in Entity e) => {
   world.Destroy(e);
};

[>1,2,3,4,5]  || Represent entities in a chunk, we iterate over them. > is the "pointer", the query.
[>1,2,3,4,5]  || .Destroy(1) is called, the first entity is being deleted. 5 Takes its place to ensure tight packed arrays.
[5,>2,3,4]    || .Destroy(2) is called, the second entity is being deleted. 4 Takes its place
[5,4,>3]       || .Destroy(3) is called, nothing takes its place ( which is correct since its the last )
[5,4]            || Query ends... and 5 and 4 are still alive. 
``` 

I could imagine that only "half" of the entities are being destroyed in such a case. A possible solution is probably to iterate backwards over every query ( like in cases where you remove items during an iteration from a list ).

But i havent done much research about that topic yet ^^

**Comment by andreakarasho** [comment]
You are right, only half of the entities get removed.
It's a change a did locally, but reverted during the PR build 😅

**Comment by andreakarasho** [comment]
Ah no rush!
This is a question I made to myself too, I need to run some benchmark.
Also thinking if it's worth to create a `ref struct` enumerator instead of using indices directly. In this way the end-user can write less code and safe code. What do you think about?

**Comment by andreakarasho** [comment]
Benchmark.
Don't ask me why, but looks much better now than before. I just updated my net7 installation, but I think the main issue was the `ref readonly Entity` which create shadow copies under the hood.

```
BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22621.963)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=7.0.101
  [Host]   : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
  ShortRun : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

|               Method |  Amount |          Mean |        Error |      StdDev | CacheMisses/Op | Allocated |
|--------------------- |-------- |--------------:|-------------:|------------:|---------------:|----------:|
|     WorldEntityQuery |   10000 |    149.444 us |    44.541 us |   2.4414 us |             31 |         - |
| EntityExtensionQuery |   10000 |    167.842 us |    52.245 us |   2.8637 us |             47 |         - |
|                Query |   10000 |     18.191 us |     4.361 us |   0.2390 us |              9 |         - |
|          EntityQuery |   10000 |     16.773 us |     7.141 us |   0.3914 us |             11 |         - |
|          StructQuery |   10000 |      8.205 us |     3.318 us |   0.1819 us |              3 |         - |
|    StructEntityQuery |   10000 |      8.089 us |     8.562 us |   0.4693 us |              6 |         - |
|     WorldEntityQuery |  100000 |  1,509.263 us |   360.464 us |  19.7582 us |         14,186 |       3 B |
| EntityExtensionQuery |  100000 |  1,688.184 us |   258.085 us |  14.1465 us |         17,557 |       3 B |
|                Query |  100000 |    203.387 us |    45.248 us |   2.4802 us |            150 |         - |
|          EntityQuery |  100000 |    179.511 us |    30.459 us |   1.6696 us |            133 |         - |
|          StructQuery |  100000 |     81.214 us |     9.133 us |   0.5006 us |             58 |         - |
|    StructEntityQuery |  100000 |     78.860 us |    28.081 us |   1.5392 us |             31 |         - |
|     WorldEntityQuery | 1000000 | 17,514.872 us | 6,142.111 us | 336.6698 us |      1,673,387 |      44 B |
| EntityExtensionQuery | 1000000 | 18,741.573 us | 2,497.304 us | 136.8857 us |      1,686,912 |      44 B |
|                Query | 1000000 |  2,435.133 us | 1,100.444 us |  60.3190 us |        256,653 |       5 B |
|          EntityQuery | 1000000 |  2,497.552 us |   182.731 us |  10.0161 us |        248,328 |       5 B |
|          StructQuery | 1000000 |  1,733.713 us |   482.972 us |  26.4733 us |        228,894 |       3 B |
|    StructEntityQuery | 1000000 |  1,735.088 us |   638.876 us |  35.0189 us |        226,520 |       3 B |
```

**Comment by genaray** [comment]
Thanks ! This actually looks pretty good :D Will totally merge this later.
Im currently trying out your changes and saw that the enumerators may break in certain scenarios...

```csharp
            foreach (ref var chunk in query.GetChunkIterator())
            {
                for (var index = chunk.Size - 1; index >= 0; index--)
                {
                    var entity = chunk.Entities[index];
                    _world.Remove<Velocity>(entity);
                }
            }
```

Destroy works fine, but in such cases the enumerator iterates over null chunks since they are being internally resized. Currently working on a solution for this, then we can proceed to merge this ^^ 

Have you looked into `Unsafe.Substract` iteration instead of `Unsafe.Add` for your changes ? I read somewhere they might be "faster" for backward iteration since the compiler/jit/cpu may notice that its an... well backwards iteration and this could probably trigger some more optimizations ^^

**Comment by andreakarasho** [comment]
I'm hitting the `null` exception if i increasae the number of entities from 100 to 100_000 too. 

____
I would say using `Unsafe.Subtract` is pretty annoying because you need to point to the latest element of `chunk.Entities[]` and go backward. It's a bit of more code to write.

```csharp
        var query = Query(in queryDescription);
        foreach (ref var chunk in query.GetChunkIterator())
        {
            var chunkSize = chunk.Size;
            if (chunkSize <= 0) continue; // branch creation, performances dropped

            ref var entityFirstElement = ref chunk.Entities[chunkSize - 1];
            for (var entityIndex = 0; entityIndex < chunkSize; ++entityIndex)
            {
                ref readonly var entity = ref Unsafe.Subtract(ref entityFirstElement, entityIndex);
                forEntity(entity);
            }
        }
```
___

I have a moc and was thinking that would be cool to expand the `struct Reference` to support the `Entity` + `Components`
```csharp
ref struct ReferenceWithEntity<TComponent0, ...>
{
    public ref Entity Entity;
    public ref TComponent0 T0;
}
```

**Comment by genaray** [comment]
I had that fixed yesterday... it also made the "ChunkEnumerator" a bit slimmer and even slightly faster. Backwards Iteration also has its advantages ^^ 

Actually the sample code could be simplified to this : 
```csharp
 var query = Query(in queryDescription);
        foreach (ref var chunk in query.GetChunkIterator())
        {
            var chunkSize = chunk.Size;
            ref var entityFirstElement = ref chunk.Entities[chunkSize - 1];
            for (var entityIndex = 0; entityIndex < chunkSize; ++entityIndex)
            {
                ref readonly var entity = ref Unsafe.Subtract(ref entityFirstElement, entityIndex);
                forEntity(entity);
            }
        }
```
Since each chunk has elements, no need to check for zero here :) However not sure if its worth the change. Just wanted to ask.


> I have a moc and was thinking that would be cool to expand the `struct Reference` to support the `Entity` + `Components`
> 
> ```cs
> ref struct ReferenceWithEntity<TComponent0, ...>
> {
>     public ref Entity Entity;
>     public ref TComponent0 T0;
> }
> ```

That actually looks pretty good, we could use this as an alternative to `References` for the query iterator ^^ 

```csharp
foreach(ref refsWithEntity in query.GetReferenceIterator<T0,T1...>)
   refsWithEntity.t0....
```

**Pull request merged**
