### PR TITLE
Fix null ref exception if calling GetEntities with a query that won't return any entites

### LINKED ISSUE #11: GetEntites throws a NullReferenceException if the world doesn't contain any entities that match the query
Repro/ UnitTest for it:

```csharp
[Test]
public void GetEntitesTest()
{
	world = World.Create();

	var archTypes = new Type[] { typeof(Transform) };
	var query = new QueryDescription { All = archTypes };

	var entity = world.Create(archTypes);

	var entites = new List<Entity>();
	world.GetEntities(query, entites);

	Assert.That(entites.Count, Is.EqualTo(1));

	entites.Clear();
	world.Destroy(entity);
	world.GetEntities(query, entites);

	Assert.That(entites.Count, Is.EqualTo(0));
}
```

### PR DESCRIPTION
**Pull request by MindSwipe**
Pretty naïve fix, just adds a `if (cunkSize == 0) continue;`, this *may* be somewhat to pretty detrimental to performance, I'll have to run the benchmarks

Fixes #11

### CODE REVIEW

**Comment by genaray** [comment]
Oh i see you already fixed the issue, thanks ! :) Gonna look at it, will also run a benchmark to verify its performance. 

If everything is fine ill merge it.

**Comment by genaray** [comment]
Quickly looked at the commit, looks great, this would actually need to be implemented for all query methods that make use of the chunk itself.

Also the source generates ones.

**Comment by genaray** [comment]
Besides that i just notice that we could just skip empty archetypes instead of running the check for each chunk. This would reduce conditions and therefore be better for performance.

**Comment by MindSwipe** [comment]
Ah ok, I'm not all too familiar with the code/ architecture yet so I didn't spot the other query methods, but skipping empty archetypes does sound like a much better solution

**Comment by genaray** [comment]
> Ah ok, I'm not all too familiar with the code/ architecture yet so I didn't spot the other query methods, but skipping empty archetypes does sound like a much better solution

Its all fine :) Im currently testing this solution, this would actually only require one single additional line code in the used Enumerators.

**Comment by genaray** [comment]
[e47d24e](https://github.com/genaray/Arch/commit/e47d24e6f2fce02d95079843030e15d1df124ff3) Fixed this issue by skipping archetypes if their size is zero.

**Pull request closed without merging**
